name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-wasi
      - uses: Swatinem/rust-cache@v2
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/aquaproj-aqua
          key: aqua-installer-${{ hashFiles('aqua.yaml') }}
          restore-keys: |
            aqua-installer-
      - uses: aquaproj/aqua-installer@v2.1.2
        env:
          AQUA_LOG_COLOR: always
        with:
          aqua_version: v2.12.1
          aqua_opts: ""
      - name: Build
        run: make sqlc.json RELEASE=1 USE_WASM_OPT=1
      - name: Collect build infomation
        id: info
        run: |
          version="v$(cargo read-manifest | jq -r .version)"
          [[ $GITHUB_REF =~ -[0-9]+$ ]] && prerelease=true || prerelease=false
          sha="$(cat target/wasm32-wasi/release/sqlc-gen-deno-postgres.wasm.sha256)"
          {
            printf 'version=%s\nprerelease=%s\nsha=%s\n' "$version" "$prerelease" "$sha"
            echo 'sqlc_json<<__EOF__'
            cat sqlc.json
            echo '__EOF__'
          } | tee -a "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          name: sqlc-gen-deno-postgres
          path: |
            target/wasm32-wasi/release/sqlc-gen-deno-postgres.wasm
            target/wasm32-wasi/release/sqlc-gen-deno-postgres.wasm.sha256
      - uses: softprops/action-gh-release@v1
        if: github.event_name == 'push'
        with:
          body: |
            ```json
            ${{ steps.info.outputs.sqlc_json }}
            ```

            ```
            ${{ steps.info.outputs.sha }}
            ```
          prerelease: ${{ fromJson(steps.info.outputs.prerelease) }}
          files: |
            target/wasm32-wasi/release/sqlc-gen-deno-postgres.wasm
            target/wasm32-wasi/release/sqlc-gen-deno-postgres.wasm.sha256
          tag_name: ${{ steps.info.outputs.version }}
